### ISSUE TITLE
Unable to resolve host "newsapi.org": No address associated with hostname

### ISSUE THREAD

**Issue by aamir-github** [philipplackner/MVVMNewsApp#40]
Internet permission is given, API key is generated but still getting the error

HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "newsapi.org": No address associated with hostname

Though the link gets called successfully (receives required data) in the browser but in the android studio, it throws the above error

**Comment by aamir-github** [comment]
The emulator was offline (not connected to the internet)...

**Comment by aman-senpai** [comment]
Thank you for your precious knowledge, fixed my error.
